### ISSUE TITLE
商品購入機能

### ISSUE THREAD

**Issue by 0g3** [bolg-developers/x#14]
## どのような機能ですか？（簡潔に）
商品を購入することができる機能です。

## なぜその機能は必要なのですか？
課金させてお金を稼ぐために必要です。

## 機能詳細
なし。

## チェックリスト
- [ ] areaラベルをつけましたか？
- [ ] priorityラベルをつけましたか？(**つくることが決定している場合**)
- [ ] 担当者をアサインしましたか？

**Comment by 0g3** [comment]
## 商品
商品はユーザーがショップで購入できるものです。少なくとも1種類以上のアイテムを少なくとも1つ以上持ちます。
### 一覧
- 医療キット
- 医療キット×6

**Comment by Nagisa-Takeuchi** [comment]
ドキュメントはKibelaに、タスク管理はAsanaに移行したため閉鎖します。
