### ISSUE TITLE
ルーム作成時に「フレンドのみ入室許可」をオプションとして指定できる

### ISSUE THREAD

**Issue by 0g3** [bolg-developers/x#21]
**どのようなアイデアですか**:

ルーム作成者が、ルーム作成時に`フレンドのみ入室可`をオプションとして指定できる。
これによって暇人が勝手に入ってくることをある程度防げるし（フレンドに暇人がいたら防げない）、手軽だと思うので、UXよさそう。
デフォルト値は、ゲームの性質上`だれでも入室可`よりも`フレンドのみ入室可`のほうがよさそう。

**Comment by Nagisa-Takeuchi** [comment]
ドキュメントはKibelaに、タスク管理はAsanaに移行したため閉鎖します。
