### ISSUE TITLE
3Dプリント改善案

### ISSUE THREAD

**Issue by Nagisa-Takeuchi** [bolg-developers/x#56]
3Dプリントしたスライドに違和感を感じる問題。
デザイナーとの議論の結果、ごつごつしたデザインに対し大きさがスマートすぎるのが違和感の原因ではないかとの結論に至った。

45口径大型オート的なスライドデザインに対し、9ミリ口径中型オート程度のサイズだった。
寸法の元にした拳銃がSIG P226(スリムな中型拳銃)だったのでこのような現象が発生したと考えられる。
そこで、Mk23(大型拳銃)の寸法に合わせ、縮尺を1.3倍にすることを3Dモデル担当に提案した。

**Comment by Nagisa-Takeuchi** [comment]
グリップが角ばり過ぎ、握りにくい問題
-->CAD上でこれ以上フィレットを掛けられないので、少し厚めに作り、プリント後に削る。

左右を合わせるためのピンが弱く、接合時に折れる問題
-->別の接合方法を模索する。

サポート上に作られる面の工作精度が悪い。
-->パーツを分割し、広い面を底面に付けるようにプリントする。

**Comment by 0g3** [comment]
@yumaa6122

**Comment by Nagisa-Takeuchi** [comment]
ドキュメントはKibelaに、タスク管理はAsanaに移行したため閉鎖します。
