### ISSUE TITLE
ルームを作成して入室するAPI

### ISSUE THREAD

**Issue by 0g3** [bolg-developers/x#65]

**Comment by hsgw-yuta** [comment]
Reqestは遅れているようだがresponseがThrowsされている
![error](https://user-images.githubusercontent.com/41692106/69487950-924b7480-0ea6-11ea-9120-0604f379bb84.png)

**Comment by hsgw-yuta** [comment]
そもそもReqest内容がおかしいかもしれない

**Comment by 0g3** [comment]
`UNAVILABLE`がRespされてる時点でちょっとおかしいかも。

https://github.com/bolg-developers/x/blob/master/projects/bolg/server/pkg/bolg/service.go#L386
この`toGRPCError`関数見るとわかると思うんだけど返してないんだよね。
```go
// 実際のコードを引用
func toGRPCError(err error) error {
	if err == nil {
		return err
	}
	switch err {
	case ErrNotFound:
		return status.Error(codes.NotFound, err.Error())
	case ErrAlreadyExists:
		return status.Error(codes.AlreadyExists, err.Error())
	case ErrInvalidToken:
		return status.Error(codes.Unauthenticated, err.Error())
	case ErrHPisZero:
		return status.Error(codes.FailedPrecondition, err.Error())
	default:
		return status.Error(codes.Internal, err.Error())
	}
}

こっちのクライアントだとつくれてるね。

```
<img width="481" alt="スクリーンショット 2019-11-24 13 51 00" src="https://user-images.githubusercontent.com/39144121/69489931-2b888400-0ec3-11ea-8341-6a6d76d99032.png">


まずちゃんとリクエストレスポンスできているのか確認するために`CheckHealth`に対する実装を書いてみるといいかもしれないね。unary rpcだと実装の難易度も下がるし。

**Comment by hsgw-yuta** [comment]
`CheckHealth`で一回作ってみます

**Comment by hsgw-yuta** [comment]
response確認できました。
![error](https://user-images.githubusercontent.com/41692106/69495077-4b8d6700-0f06-11ea-86b9-8b6def52f7c2.png)

**Comment by hsgw-yuta** [comment]
streamのresponse確認
![error](https://user-images.githubusercontent.com/41692106/69495856-f144d400-0f0e-11ea-8174-089555f55601.png)

**Comment by 0g3** [comment]
素晴らしい！！
その調子で行こう！笑

**Comment by Nagisa-Takeuchi** [comment]
ドキュメントはKibelaに、タスク管理はAsanaに移行したため閉鎖します。
